### ISSUE TITLE
Datadog Dashboards error on version 2.8

### ISSUE THREAD

**Issue by mallyx3** [terraform-providers/terraform-provider-datadog#531]
Hi there,

Im using provider version 2.8 and i'm encountering this bug:

```
Error: error checking dashboard exists: Data failed to match schemas in oneOf(WidgetDefinition):
```

I had previously imported some datadog dashboards into terraform using version 2.7, but now on terraform plan, I am constantly returned this error. Forcing version 2.7 seems to work.
Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.12.26

### Affected Resource(s)
datadog_dashboard

### Expected Behavior
terraform plan would indicate no expected changes. 

### Actual Behavior
terraform plan gave this error
```
Error: error checking dashboard exists: Data failed to match schemas in oneOf(WidgetDefinition):
```

### Steps to Reproduce
1. Using provider "datadog" version 2.8
2. terraform plan fails
3. using version 2.7
4. terraform plan succeeds

**Comment by gzussa** [comment]
Hi, Thanks for reporting this issue. Would you mind to share your widget TF config? my guess is that values you are using are missing in this new version :/

**Comment by onematchfox** [comment]
@gzussa Here's a fairly simple Apache dashboard that is broken (I have many others and all are broken)

```
resource "datadog_dashboard" "apache" {
  title        = "Apache"
  layout_type  = "free"
  is_read_only = true

  template_variable {
    name    = "service"
    prefix  = "service/component"
    default = var.service
  }

  template_variable {
    name    = "region"
    prefix  = "region"
    default = "*"
  }

  template_variable {
    name    = "environment"
    prefix  = "environment"
    default = "*"
  }

  widget {
    image_definition {
      url    = "--redacted--"
      sizing = "zoom"
    }
    layout = {
      x      = 1
      y      = 1
      width  = 17
      height = 11
    }
  }

  widget {
    image_definition {
      url    = "--redacted--"
      sizing = "center"
    }
    layout = {
      x      = 1
      y      = 13
      width  = 17
      height = 12
    }
  }

  widget {
    note_definition {
      content          = "**Availability**"
      text_align       = "center"
      font_size        = "18"
      tick_pos         = "50%"
      show_tick        = true
      tick_edge        = "bottom"
      background_color = "gray"
    }
    layout = {
      x      = 1
      y      = 26
      width  = 17
      height = 5
    }
  }

  widget {
    check_status_definition {
      title       = "Server can connect"
      title_align = "center"
      title_size  = 16

      check    = "apache.can_connect"
      grouping = "cluster"

      tags = [
        "$service",
        "$region",
        "$environment",
      ]

      time = {
        live_span = "10m"
      }
    }
    layout = {
      x      = 1
      y      = 33
      width  = 17
      height = 13
    }
  }

  widget {
    query_value_definition {
      title       = "Min Uptime"
      title_align = "left"
      title_size  = 16

      autoscale = true

      request {
        q          = "min:apache.performance.uptime{$service,$region,$environment}"
        aggregator = "last"

        conditional_formats {
          palette    = "white_on_green"
          value      = 0
          comparator = ">"
        }
      }
    }
    layout = {
      x      = 1
      y      = 48
      width  = 17
      height = 13
    }
  }

  widget {
    note_definition {
      content          = "**Throughput**"
      text_align       = "center"
      font_size        = "18"
      tick_pos         = "50%"
      show_tick        = true
      tick_edge        = "bottom"
      background_color = "gray"
    }
    layout = {
      x      = 20
      y      = 1
      width  = 47
      height = 5
    }
  }

  widget {
    timeseries_definition {
      title       = "Rate of requests (per region)"
      title_align = "left"
      title_size  = 16

      request {
        q            = "sum:apache.net.request_per_s{$service,$region,$environment} by {region}"
        display_type = "line"

        style {
          palette    = "cool"
          line_type  = "solid"
          line_width = "normal"
        }
      }
    }
    layout = {
      x      = 20
      y      = 8
      width  = 47
      height = 17
    }
  }

  widget {
    timeseries_definition {
      title       = "Bytes served (per region)"
      title_align = "left"
      title_size  = 16

      request {
        q            = "sum:apache.net.bytes_per_s{$service,$region,$environment} by {region}"
        display_type = "line"

        style {
          palette    = "cool"
          line_type  = "solid"
          line_width = "normal"
        }
      }
    }
    layout = {
      x      = 20
      y      = 26
      width  = 47
      height = 17
    }
  }

  widget {
    timeseries_definition {
      title       = "Requests per second (per region)"
      title_align = "left"
      title_size  = 16

      request {
        q            = "avg:apache.net.request_per_s{$service,$region,$environment} by {region}"
        display_type = "line"

        style {
          palette    = "cool"
          line_type  = "solid"
          line_width = "normal"
        }
      }
    }
    layout = {
      x      = 20
      y      = 44
      width  = 47
      height = 17
    }
  }

  widget {
    note_definition {
      content          = "**Resource Utilisation**"
      text_align       = "center"
      font_size        = "18"
      tick_pos         = "50%"
      show_tick        = true
      tick_edge        = "bottom"
      background_color = "gray"
    }
    layout = {
      x      = 69
      y      = 1
      width  = 53
      height = 5
    }
  }

  widget {
    toplist_definition {
      title       = "Apache process CPU usage (top 10 containers)"
      title_align = "left"
      title_size  = 16

      request {
        q = "top(avg:apache.performance.cpu_load{$service,$region,$environment,short_image:shibboleth} by {region,image_tag,ecs_container_name}, 10, 'mean', 'desc')"

        style {
          palette = "dog_classic"
        }
      }
    }
    layout = {
      x      = 69
      y      = 8
      width  = 53
      height = 32
    }
  }

  widget {
    timeseries_definition {
      title       = "Busy vs. idle worker threads"
      title_align = "left"
      title_size  = 16

      request {
        q            = "sum:apache.performance.idle_workers{$service,$region,$environment}, sum:apache.performance.busy_workers{$service,$region,$environment}"
        display_type = "area"

        style {
          palette    = "cool"
          line_type  = "solid"
          line_width = "normal"
        }
      }
    }
    layout = {
      x      = 69
      y      = 41
      width  = 53
      height = 20
    }
  }

  widget {
    note_definition {
      content          = "**Connection Status**"
      text_align       = "center"
      font_size        = "18"
      tick_pos         = "50%"
      show_tick        = true
      tick_edge        = "bottom"
      background_color = "gray"
    }
    layout = {
      x      = 124
      y      = 1
      width  = 47
      height = 5
    }
  }

  widget {
    timeseries_definition {
      title       = "Async connections: writing, keep-alive, closing"
      title_align = "left"
      title_size  = 16

      request {
        q            = "sum:apache.conns_async_closing{$service,$region,$environment}.rollup(max), sum:apache.conns_async_writing{$service,$region,$environment}.rollup(max), sum:apache.conns_async_keep_alive{$service,$region,$environment}.rollup(max)"
        display_type = "bars"

        style {
          palette    = "cool"
          line_type  = "solid"
          line_width = "normal"
        }
      }
    }
    layout = {
      x      = 124
      y      = 8
      width  = 47
      height = 17
    }
  }

  widget {
    timeseries_definition {
      title       = "Total async connections"
      title_align = "left"
      title_size  = 16

      request {
        q            = "sum:apache.conns_total{$service,$region,$environment} by {region}.rollup(max)"
        display_type = "bars"

        style {
          palette    = "cool"
          line_type  = "solid"
          line_width = "normal"
        }
      }
    }
    layout = {
      x      = 124
      y      = 26
      width  = 47
      height = 17
    }
  }
}
```

**Comment by gzussa** [comment]
Ok thanks. Let me test this out

**Comment by gzussa** [comment]
I created a test to reproduce the issue in the following PR #533. I am using the same config above mentioned. However, as you can see my test is passing. Are you sure this config is not working? Do you mind to take a look. Thanks

**Comment by gzussa** [comment]
Ok, maybe the problem is somewhere else. Could you go to your dashboard and export it as JSON. From there could you tell me what the value for `legend_size` is? If you see `0` somewhere, then it is most probably the problem. We already have a PR in our Go Client that add the 0 value to the legend_size enum (https://github.com/DataDog/datadog-api-client-go/pull/336). Please, let me know.

**Comment by Towerthousand** [comment]
I'm also seeing this regression. Problem happens even if I just add a group to the dashboard.  Seems like making virtually any change to a dashboard that is in the state will make subsequent plans fail. For now reverting back to `2.7.0`

Here's the json of the dash before the manual modification:

```
{"title":"[redis-test-project - dev]  Infrastructure","description":"","widgets":[{"id":4974544728634463,"definition":{"type":"group","layout_type":"ordered","widgets":[{"id":6552555832516807,"definition":{"type":"timeseries","requests":[{"q":"avg:jvm.gc.major_collection_time{project:redis-test-project,env:dev}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"avg:jvm.gc.minor_collection_time{project:redis-test-project,env:dev}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Average Java GC duration","show_legend":false,"legend_size":"0"}},{"id":2116518263394656,"definition":{"type":"timeseries","requests":[{"q":"sum:jvm.gc.major_collection_count{project:redis-test-project,env:dev}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"sum:jvm.gc.minor_collection_count{project:redis-test-project,env:dev}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Average Java GC count","show_legend":false,"legend_size":"0"}},{"id":4515355701001171,"definition":{"type":"timeseries","requests":[{"q":"avg:jvm.cpu_load.system{project:redis-test-project,env:dev}","metadata":[{"expression":"avg:jvm.cpu_load.system{project:redis-test-project,env:dev}","alias_name":"system"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"avg:jvm.cpu_load.process{owner:redis-test-project,env:dev}","metadata":[{"expression":"avg:jvm.cpu_load.process{owner:redis-test-project,env:dev}","alias_name":"process"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Average JVM CPU load vs System CPU load","show_legend":false,"legend_size":"0"}},{"id":3580875662141371,"definition":{"type":"timeseries","requests":[{"q":"avg:jvm.gc.major_collection_time{project:redis-test-project,env:dev} by {host}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Major GC duration by host","show_legend":false,"legend_size":"0"}},{"id":8264105373951146,"definition":{"type":"timeseries","requests":[{"q":"avg:jvm.heap_memory{project:redis-test-project,env:dev}","metadata":[{"expression":"avg:jvm.heap_memory{project:redis-test-project,env:dev}","alias_name":"used"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"avg:jvm.heap_memory_max{owner:redis-test-project,env:dev}","metadata":[{"expression":"avg:jvm.heap_memory_max{owner:redis-test-project,env:dev}","alias_name":"max"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"avg:jvm.heap_memory_init{owner:redis-test-project,env:dev}","metadata":[{"expression":"avg:jvm.heap_memory_init{owner:redis-test-project,env:dev}","alias_name":"init"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"avg:jvm.heap_memory_committed{owner:redis-test-project,env:dev}","metadata":[{"expression":"avg:jvm.heap_memory_committed{owner:redis-test-project,env:dev}","alias_name":"commited"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Average Heap Memory","show_legend":false,"legend_size":"0"}},{"id":6417315735182858,"definition":{"type":"timeseries","requests":[{"q":"avg:jvm.non_heap_memory{project:redis-test-project,env:dev}","metadata":[{"expression":"avg:jvm.non_heap_memory{project:redis-test-project,env:dev}","alias_name":"used"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"avg:jvm.non_heap_memory_max{owner:redis-test-project,env:dev}","metadata":[{"expression":"avg:jvm.non_heap_memory_max{owner:redis-test-project,env:dev}","alias_name":"max"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"avg:jvm.heap_memory_init{owner:redis-test-project,env:dev}","metadata":[{"expression":"avg:jvm.heap_memory_init{owner:redis-test-project,env:dev}","alias_name":"init"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"avg:jvm.heap_memory_committed{owner:redis-test-project,env:dev}","metadata":[{"expression":"avg:jvm.heap_memory_committed{owner:redis-test-project,env:dev}","alias_name":"commited"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Average Non-Heap Memory","show_legend":false,"legend_size":"0"}},{"id":3075919006276392,"definition":{"type":"timeseries","requests":[{"q":"sum:jvm.thread_count{project:redis-test-project,env:dev} by {host}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Thread count by host","show_legend":false,"legend_size":"0"}},{"id":2124694048279474,"definition":{"type":"timeseries","requests":[{"q":"sum:jvm.os.open_file_descriptors{project:redis-test-project,env:dev} by {host}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"JVM File descriptors per host","show_legend":false,"legend_size":"0"}},{"id":2864368151479128,"definition":{"type":"timeseries","requests":[{"q":"sum:jvm.loaded_classes{project:redis-test-project,env:dev} by {host}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Loaded classes per host","show_legend":false,"legend_size":"0"}}],"title":"JVM Metrics"}},{"id":590479242029866,"definition":{"type":"group","layout_type":"ordered","widgets":[{"id":2827816104275655,"definition":{"type":"hostmap","requests":{"fill":{"q":"avg:system.cpu.user{project:redis-test-project,env:dev,iam_profile:redis-test-project-dev} by {host}"}},"title":"Host health (red is > 75% CPU)","node_type":"host","no_metric_hosts":true,"no_group_hosts":false,"group":["autoscaling_group","availability-zone"],"scope":["project:redis-test-project","env:dev","iam_profile:redis-test-project-dev"],"style":{"palette":"green_to_orange","palette_flip":false,"fill_min":"40","fill_max":"75"}}},{"id":4057854270404057,"definition":{"type":"timeseries","requests":[{"q":"avg:system.cpu.user{project:redis-test-project,env:dev} by {host}","metadata":[{"expression":"avg:system.cpu.user{project:redis-test-project,env:dev} by {host}","alias_name":"per_host"}],"display_type":"line","style":{"palette":"purple","line_type":"dashed","line_width":"thin"}},{"q":"avg:system.cpu.user{project:redis-test-project,env:dev}","metadata":[{"expression":"avg:system.cpu.user{project:redis-test-project,env:dev}","alias_name":"avg"}],"display_type":"line","style":{"palette":"cool","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"CPU Usage per host & avg","show_legend":false,"legend_size":"0"}},{"id":1635375133165586,"definition":{"type":"timeseries","requests":[{"q":"avg:system.cpu.iowait{project:redis-test-project,env:dev} by {host}","display_type":"line","style":{"palette":"purple","line_type":"dashed","line_width":"thin"}},{"q":"avg:system.cpu.iowait{project:redis-test-project,env:dev}","display_type":"line","style":{"palette":"cool","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"CPU IO % per host & avg","show_legend":false,"legend_size":"0"}},{"id":3509120134787992,"definition":{"type":"timeseries","requests":[{"q":"avg:system.cpu.user{project:redis-test-project,env:dev}","metadata":[{"expression":"avg:system.cpu.user{project:redis-test-project,env:dev}","alias_name":"User"}],"display_type":"area","style":{"palette":"cool","line_type":"solid","line_width":"normal"}},{"q":"avg:system.cpu.iowait{project:redis-test-project,env:dev}","metadata":[{"expression":"avg:system.cpu.iowait{project:redis-test-project,env:dev}","alias_name":"IO"}],"display_type":"area","style":{"palette":"cool","line_type":"solid","line_width":"normal"}},{"q":"avg:system.cpu.system{project:redis-test-project,env:dev}","metadata":[{"expression":"avg:system.cpu.system{project:redis-test-project,env:dev}","alias_name":"System"}],"display_type":"area","style":{"palette":"cool","line_type":"solid","line_width":"normal"}},{"q":"avg:system.cpu.idle{project:redis-test-project,env:dev}","metadata":[{"expression":"avg:system.cpu.idle{project:redis-test-project,env:dev}","alias_name":"Idle"}],"display_type":"area","style":{"palette":"cool","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"CPU Time breakdown avg","show_legend":false,"legend_size":"0"}},{"id":7616239523504065,"definition":{"type":"timeseries","requests":[{"q":"avg:system.mem.used{project:redis-test-project,env:dev} by {host}","metadata":[{"expression":"avg:system.mem.used{project:redis-test-project,env:dev} by {host}","alias_name":"per_host"}],"display_type":"line","style":{"palette":"purple","line_type":"dashed","line_width":"thin"}},{"q":"avg:system.mem.used{project:redis-test-project,env:dev}","metadata":[{"expression":"avg:system.mem.used{project:redis-test-project,env:dev}","alias_name":"avg"}],"display_type":"line","style":{"palette":"cool","line_type":"solid","line_width":"normal"}}],"yaxis":{"min":"0","include_zero":false},"title":"Used memory per host per host & avg","show_legend":false,"legend_size":"0"}},{"id":2421619433180397,"definition":{"type":"timeseries","requests":[{"q":"avg:system.fs.file_handles.max{project:redis-test-project,env:dev}","metadata":[{"expression":"avg:system.fs.file_handles.max{project:redis-test-project,env:dev}","alias_name":"system_max"}],"display_type":"line","style":{"palette":"purple","line_type":"solid","line_width":"normal"}},{"q":"avg:system.fs.file_handles.used{project:redis-test-project,env:dev}","metadata":[{"expression":"avg:system.fs.file_handles.used{project:redis-test-project,env:dev}","alias_name":"system_used"}],"display_type":"line","style":{"palette":"cool","line_type":"solid","line_width":"normal"}}],"yaxis":{"min":"0","include_zero":false},"title":"Max & used file descriptor avg","show_legend":false,"legend_size":"0"}}],"title":"Compute"}},{"id":8521076959601471,"definition":{"type":"group","layout_type":"ordered","widgets":[{"id":595671202145353,"definition":{"type":"query_value","requests":[{"q":"sum:aws.applicationelb.request_count{project:redis-test-project,env:dev}.as_count().rollup(sum, 60)","aggregator":"avg"}],"title":"Requests per minute","autoscale":true,"custom_unit":"rpm","precision":2}},{"id":5122057787877346,"definition":{"type":"timeseries","requests":[{"q":"sum:aws.applicationelb.httpcode_elb_5xx{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}.as_count()","metadata":[{"expression":"sum:aws.applicationelb.httpcode_elb_5xx{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}.as_count()","alias_name":"500"}],"display_type":"line","style":{"palette":"warm","line_type":"solid","line_width":"normal"}},{"q":"sum:aws.applicationelb.httpcode_elb_4xx{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}.as_count()","metadata":[{"expression":"sum:aws.applicationelb.httpcode_elb_4xx{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}.as_count()","alias_name":"400"}],"display_type":"line","style":{"palette":"orange","line_type":"solid","line_width":"normal"}},{"q":"sum:aws.applicationelb.httpcode_elb_3xx{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}.as_count()","metadata":[{"expression":"sum:aws.applicationelb.httpcode_elb_3xx{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}.as_count()","alias_name":"300"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"sum:aws.applicationelb.httpcode_target_2xx{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}.as_count()","metadata":[{"expression":"sum:aws.applicationelb.httpcode_target_2xx{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}.as_count()","alias_name":"200"}],"display_type":"line","style":{"palette":"cool","line_type":"solid","line_width":"normal"}},{"q":"sum:aws.applicationelb.request_count{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}.as_count()","metadata":[{"expression":"sum:aws.applicationelb.request_count{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}.as_count()","alias_name":"total"}],"display_type":"line","style":{"palette":"cool","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Request count per response code","show_legend":false,"legend_size":"0"}},{"id":5838048957845154,"definition":{"type":"timeseries","requests":[{"q":"avg:aws.applicationelb.processed_bytes{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}.as_count()","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Processed bytes","show_legend":false,"legend_size":"0"}},{"id":651928676482307,"definition":{"type":"timeseries","requests":[{"q":"avg:aws.applicationelb.target_response_time.p50{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}","metadata":[{"expression":"avg:aws.applicationelb.target_response_time.p50{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}","alias_name":"p50"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"avg:aws.applicationelb.target_response_time.p95{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}","metadata":[{"expression":"avg:aws.applicationelb.target_response_time.p95{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}","alias_name":"p95"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"avg:aws.applicationelb.target_response_time.average{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}","metadata":[{"expression":"avg:aws.applicationelb.target_response_time.average{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}","alias_name":"avg"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"avg:aws.applicationelb.target_response_time.p99{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}","metadata":[{"expression":"avg:aws.applicationelb.target_response_time.p99{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}","alias_name":"p99"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Target response time","show_legend":false,"legend_size":"0"}},{"id":1466420699109595,"definition":{"type":"timeseries","requests":[{"q":"sum:aws.applicationelb.healthy_host_count{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}","display_type":"area","style":{"palette":"cool","line_type":"solid","line_width":"normal"}},{"q":"sum:aws.applicationelb.un_healthy_host_count{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}","display_type":"area","style":{"palette":"warm","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Healthy vs unhealthy host count","show_legend":false,"legend_size":"0"}},{"id":3443243647363338,"definition":{"type":"timeseries","requests":[{"q":"sum:aws.applicationelb.rule_evaluations{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}.as_count()","display_type":"area","style":{"palette":"cool","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"ALB Rule evaluations","show_legend":false,"legend_size":"0"}}],"title":"External Load Balancer"}}],"template_variables":[],"layout_type":"ordered","is_read_only":false,"notify_list":[],"id":"xc7-twd-m23"}
```

and this is the json after:
```
{"title":"[redis-test-project - dev]  Infrastructure","description":"","widgets":[{"id":4974544728634463,"definition":{"type":"group","layout_type":"ordered","widgets":[{"id":6552555832516807,"definition":{"type":"timeseries","requests":[{"q":"avg:jvm.gc.major_collection_time{project:redis-test-project,env:dev}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"avg:jvm.gc.minor_collection_time{project:redis-test-project,env:dev}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Average Java GC duration","show_legend":false,"legend_size":"0"}},{"id":2116518263394656,"definition":{"type":"timeseries","requests":[{"q":"sum:jvm.gc.major_collection_count{project:redis-test-project,env:dev}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"sum:jvm.gc.minor_collection_count{project:redis-test-project,env:dev}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Average Java GC count","show_legend":false,"legend_size":"0"}},{"id":4515355701001171,"definition":{"type":"timeseries","requests":[{"q":"avg:jvm.cpu_load.system{project:redis-test-project,env:dev}","metadata":[{"expression":"avg:jvm.cpu_load.system{project:redis-test-project,env:dev}","alias_name":"system"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"avg:jvm.cpu_load.process{owner:redis-test-project,env:dev}","metadata":[{"expression":"avg:jvm.cpu_load.process{owner:redis-test-project,env:dev}","alias_name":"process"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Average JVM CPU load vs System CPU load","show_legend":false,"legend_size":"0"}},{"id":3580875662141371,"definition":{"type":"timeseries","requests":[{"q":"avg:jvm.gc.major_collection_time{project:redis-test-project,env:dev} by {host}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Major GC duration by host","show_legend":false,"legend_size":"0"}},{"id":8264105373951146,"definition":{"type":"timeseries","requests":[{"q":"avg:jvm.heap_memory{project:redis-test-project,env:dev}","metadata":[{"expression":"avg:jvm.heap_memory{project:redis-test-project,env:dev}","alias_name":"used"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"avg:jvm.heap_memory_max{owner:redis-test-project,env:dev}","metadata":[{"expression":"avg:jvm.heap_memory_max{owner:redis-test-project,env:dev}","alias_name":"max"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"avg:jvm.heap_memory_init{owner:redis-test-project,env:dev}","metadata":[{"expression":"avg:jvm.heap_memory_init{owner:redis-test-project,env:dev}","alias_name":"init"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"avg:jvm.heap_memory_committed{owner:redis-test-project,env:dev}","metadata":[{"expression":"avg:jvm.heap_memory_committed{owner:redis-test-project,env:dev}","alias_name":"commited"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Average Heap Memory","show_legend":false,"legend_size":"0"}},{"id":6417315735182858,"definition":{"type":"timeseries","requests":[{"q":"avg:jvm.non_heap_memory{project:redis-test-project,env:dev}","metadata":[{"expression":"avg:jvm.non_heap_memory{project:redis-test-project,env:dev}","alias_name":"used"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"avg:jvm.non_heap_memory_max{owner:redis-test-project,env:dev}","metadata":[{"expression":"avg:jvm.non_heap_memory_max{owner:redis-test-project,env:dev}","alias_name":"max"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"avg:jvm.heap_memory_init{owner:redis-test-project,env:dev}","metadata":[{"expression":"avg:jvm.heap_memory_init{owner:redis-test-project,env:dev}","alias_name":"init"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"avg:jvm.heap_memory_committed{owner:redis-test-project,env:dev}","metadata":[{"expression":"avg:jvm.heap_memory_committed{owner:redis-test-project,env:dev}","alias_name":"commited"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Average Non-Heap Memory","show_legend":false,"legend_size":"0"}},{"id":3075919006276392,"definition":{"type":"timeseries","requests":[{"q":"sum:jvm.thread_count{project:redis-test-project,env:dev} by {host}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Thread count by host","show_legend":false,"legend_size":"0"}},{"id":2124694048279474,"definition":{"type":"timeseries","requests":[{"q":"sum:jvm.os.open_file_descriptors{project:redis-test-project,env:dev} by {host}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"JVM File descriptors per host","show_legend":false,"legend_size":"0"}},{"id":2864368151479128,"definition":{"type":"timeseries","requests":[{"q":"sum:jvm.loaded_classes{project:redis-test-project,env:dev} by {host}","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Loaded classes per host","show_legend":false,"legend_size":"0"}}],"title":"JVM Metrics"}},{"id":590479242029866,"definition":{"type":"group","layout_type":"ordered","widgets":[{"id":2827816104275655,"definition":{"type":"hostmap","requests":{"fill":{"q":"avg:system.cpu.user{project:redis-test-project,env:dev,iam_profile:redis-test-project-dev} by {host}"}},"title":"Host health (red is > 75% CPU)","node_type":"host","no_metric_hosts":true,"no_group_hosts":false,"group":["autoscaling_group","availability-zone"],"scope":["project:redis-test-project","env:dev","iam_profile:redis-test-project-dev"],"style":{"palette":"green_to_orange","palette_flip":false,"fill_min":"40","fill_max":"75"}}},{"id":4057854270404057,"definition":{"type":"timeseries","requests":[{"q":"avg:system.cpu.user{project:redis-test-project,env:dev} by {host}","metadata":[{"expression":"avg:system.cpu.user{project:redis-test-project,env:dev} by {host}","alias_name":"per_host"}],"display_type":"line","style":{"palette":"purple","line_type":"dashed","line_width":"thin"}},{"q":"avg:system.cpu.user{project:redis-test-project,env:dev}","metadata":[{"expression":"avg:system.cpu.user{project:redis-test-project,env:dev}","alias_name":"avg"}],"display_type":"line","style":{"palette":"cool","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"CPU Usage per host & avg","show_legend":false,"legend_size":"0"}},{"id":1635375133165586,"definition":{"type":"timeseries","requests":[{"q":"avg:system.cpu.iowait{project:redis-test-project,env:dev} by {host}","display_type":"line","style":{"palette":"purple","line_type":"dashed","line_width":"thin"}},{"q":"avg:system.cpu.iowait{project:redis-test-project,env:dev}","display_type":"line","style":{"palette":"cool","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"CPU IO % per host & avg","show_legend":false,"legend_size":"0"}},{"id":3509120134787992,"definition":{"type":"timeseries","requests":[{"q":"avg:system.cpu.user{project:redis-test-project,env:dev}","metadata":[{"expression":"avg:system.cpu.user{project:redis-test-project,env:dev}","alias_name":"User"}],"display_type":"area","style":{"palette":"cool","line_type":"solid","line_width":"normal"}},{"q":"avg:system.cpu.iowait{project:redis-test-project,env:dev}","metadata":[{"expression":"avg:system.cpu.iowait{project:redis-test-project,env:dev}","alias_name":"IO"}],"display_type":"area","style":{"palette":"cool","line_type":"solid","line_width":"normal"}},{"q":"avg:system.cpu.system{project:redis-test-project,env:dev}","metadata":[{"expression":"avg:system.cpu.system{project:redis-test-project,env:dev}","alias_name":"System"}],"display_type":"area","style":{"palette":"cool","line_type":"solid","line_width":"normal"}},{"q":"avg:system.cpu.idle{project:redis-test-project,env:dev}","metadata":[{"expression":"avg:system.cpu.idle{project:redis-test-project,env:dev}","alias_name":"Idle"}],"display_type":"area","style":{"palette":"cool","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"CPU Time breakdown avg","show_legend":false,"legend_size":"0"}},{"id":7616239523504065,"definition":{"type":"timeseries","requests":[{"q":"avg:system.mem.used{project:redis-test-project,env:dev} by {host}","metadata":[{"expression":"avg:system.mem.used{project:redis-test-project,env:dev} by {host}","alias_name":"per_host"}],"display_type":"line","style":{"palette":"purple","line_type":"dashed","line_width":"thin"}},{"q":"avg:system.mem.used{project:redis-test-project,env:dev}","metadata":[{"expression":"avg:system.mem.used{project:redis-test-project,env:dev}","alias_name":"avg"}],"display_type":"line","style":{"palette":"cool","line_type":"solid","line_width":"normal"}}],"yaxis":{"min":"0","include_zero":false},"title":"Used memory per host per host & avg","show_legend":false,"legend_size":"0"}},{"id":2421619433180397,"definition":{"type":"timeseries","requests":[{"q":"avg:system.fs.file_handles.max{project:redis-test-project,env:dev}","metadata":[{"expression":"avg:system.fs.file_handles.max{project:redis-test-project,env:dev}","alias_name":"system_max"}],"display_type":"line","style":{"palette":"purple","line_type":"solid","line_width":"normal"}},{"q":"avg:system.fs.file_handles.used{project:redis-test-project,env:dev}","metadata":[{"expression":"avg:system.fs.file_handles.used{project:redis-test-project,env:dev}","alias_name":"system_used"}],"display_type":"line","style":{"palette":"cool","line_type":"solid","line_width":"normal"}}],"yaxis":{"min":"0","include_zero":false},"title":"Max & used file descriptor avg","show_legend":false,"legend_size":"0"}}],"title":"Compute"}},{"id":8521076959601471,"definition":{"type":"group","layout_type":"ordered","widgets":[{"id":595671202145353,"definition":{"type":"query_value","requests":[{"q":"sum:aws.applicationelb.request_count{project:redis-test-project,env:dev}.as_count().rollup(sum, 60)","aggregator":"avg"}],"title":"Requests per minute","autoscale":true,"custom_unit":"rpm","precision":2}},{"id":5122057787877346,"definition":{"type":"timeseries","requests":[{"q":"sum:aws.applicationelb.httpcode_elb_5xx{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}.as_count()","metadata":[{"expression":"sum:aws.applicationelb.httpcode_elb_5xx{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}.as_count()","alias_name":"500"}],"display_type":"line","style":{"palette":"warm","line_type":"solid","line_width":"normal"}},{"q":"sum:aws.applicationelb.httpcode_elb_4xx{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}.as_count()","metadata":[{"expression":"sum:aws.applicationelb.httpcode_elb_4xx{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}.as_count()","alias_name":"400"}],"display_type":"line","style":{"palette":"orange","line_type":"solid","line_width":"normal"}},{"q":"sum:aws.applicationelb.httpcode_elb_3xx{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}.as_count()","metadata":[{"expression":"sum:aws.applicationelb.httpcode_elb_3xx{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}.as_count()","alias_name":"300"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"sum:aws.applicationelb.httpcode_target_2xx{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}.as_count()","metadata":[{"expression":"sum:aws.applicationelb.httpcode_target_2xx{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}.as_count()","alias_name":"200"}],"display_type":"line","style":{"palette":"cool","line_type":"solid","line_width":"normal"}},{"q":"sum:aws.applicationelb.request_count{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}.as_count()","metadata":[{"expression":"sum:aws.applicationelb.request_count{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}.as_count()","alias_name":"total"}],"display_type":"line","style":{"palette":"cool","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Request count per response code","show_legend":false,"legend_size":"0"}},{"id":5838048957845154,"definition":{"type":"timeseries","requests":[{"q":"avg:aws.applicationelb.processed_bytes{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}.as_count()","display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Processed bytes","show_legend":false,"legend_size":"0"}},{"id":651928676482307,"definition":{"type":"timeseries","requests":[{"q":"avg:aws.applicationelb.target_response_time.p50{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}","metadata":[{"expression":"avg:aws.applicationelb.target_response_time.p50{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}","alias_name":"p50"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"avg:aws.applicationelb.target_response_time.p95{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}","metadata":[{"expression":"avg:aws.applicationelb.target_response_time.p95{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}","alias_name":"p95"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"avg:aws.applicationelb.target_response_time.average{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}","metadata":[{"expression":"avg:aws.applicationelb.target_response_time.average{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}","alias_name":"avg"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}},{"q":"avg:aws.applicationelb.target_response_time.p99{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}","metadata":[{"expression":"avg:aws.applicationelb.target_response_time.p99{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}","alias_name":"p99"}],"display_type":"line","style":{"palette":"dog_classic","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Target response time","show_legend":false,"legend_size":"0"}},{"id":1466420699109595,"definition":{"type":"timeseries","requests":[{"q":"sum:aws.applicationelb.healthy_host_count{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}","display_type":"area","style":{"palette":"cool","line_type":"solid","line_width":"normal"}},{"q":"sum:aws.applicationelb.un_healthy_host_count{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}","display_type":"area","style":{"palette":"warm","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"Healthy vs unhealthy host count","show_legend":false,"legend_size":"0"}},{"id":3443243647363338,"definition":{"type":"timeseries","requests":[{"q":"sum:aws.applicationelb.rule_evaluations{project:redis-test-project,name:redis-test-project-dev-elb-ext,env:dev}.as_count()","display_type":"area","style":{"palette":"cool","line_type":"solid","line_width":"normal"}}],"yaxis":{"scale":"linear","min":"auto","max":"auto","include_zero":true},"title":"ALB Rule evaluations","show_legend":false,"legend_size":"0"}}],"title":"External Load Balancer"}},{"id":4441986428420102,"definition":{"type":"group","layout_type":"ordered","widgets":[],"title":"Redis"}}],"template_variables":[],"layout_type":"ordered","is_read_only":false,"notify_list":[],"id":"xc7-twd-m23"}
```

**Comment by steveh** [comment]
I'm also getting errors with version 2.8.0. Version 2.7.0 is fine. 

For people searching: `Error: rpc error: code = Canceled desc = context canceled`

**Comment by mmshin** [comment]
So we're also having this exact error and as suggested above exported json shows `"legend_size":"0"`

**Comment by gzussa** [comment]
This issue should be fixed with the upcoming 2.9.0 release. See https://github.com/terraform-providers/terraform-provider-datadog/pull/546

**Comment by gzussa** [comment]
The release is actually `2.9.0`. See https://github.com/terraform-providers/terraform-provider-datadog/releases/tag/v2.9.0. Closing this issue.

**Comment by onematchfox** [comment]
@gzussa Sorry for the slow response. Afraid to say I'm still seeing this issue on `2.9.0`  (and even on `2.12.1`); albeit on a different dashboard now. Exported existing dashboard as suggested and all instances of `legend_size` are `"legend_size": ""`. Could this be the problem?

**Comment by gzussa** [comment]
Hi @onematchfox, I will let @therve follow up at this point 🙇‍♂️

**Comment by therve** [comment]
Hi @onematchfox 

I think I reproduced the issue. In the short term, what you can do is export the dashboards with the problem to JSON, replace `"legend_size": ""` with `"legend_size: "0"` and reimport them.

I'm talking to the backend team to see how to proceed with this. We'll ever change the backend, in which case it should work transparently, or remove the constraint in the client side.

Thanks for your patience.

**Comment by onematchfox** [comment]
Thanks @therve. Your suggestion did the trick. All working now.
